// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> cropPng({
  required List<int> input,
  required int x,
  required int y,
  required int w,
  required int h,
}) =>
    RustLib.instance.api.crateApiCropPng(input: input, x: x, y: y, w: w, h: h);
